import { Property, PropertyType } from './types';

export const COMMUNES = [
  'Concepción',
  'Chiguayante',
  'San Pedro de la Paz',
  'Talcahuano',
  'Coronel',
  'Penco',
  'Los Ángeles'
];

export const MOCK_PROPERTIES: Property[] = [
  // --- Propiedades Internacionales (Existentes) ---
  {
    id: '1',
    title: 'Villa Moderna Frente al Mar',
    subtitle: 'Lujo costero redefinido en la Costa del Sol',
    location: 'Marbella, España',
    price: 4500000,
    currency: '€',
    imageUrl: 'https://picsum.photos/seed/leroy1/800/600',
    bedrooms: 5,
    bathrooms: 6,
    area: 650,
    type: PropertyType.VILLA,
    description: 'Espectacular villa moderna con acceso directo a la playa y vistas panorámicas al Mediterráneo. Acabados de mármol italiano y domótica integral.',
    amenities: ['Piscina Privada', 'Vista al Mar', 'Seguridad 24/7', 'Domótica', 'Gimnasio'],
    isPremium: true
  },
  {
    id: '5',
    title: 'Residencia Exclusiva en Pedregal',
    subtitle: 'Arquitectura monumental en los acantilados de Cabo',
    location: 'Cabo San Lucas, México',
    price: 12500000,
    currency: '$',
    imageUrl: 'https://images.unsplash.com/photo-1512813195386-6cf811ad3542?q=80&w=800&auto=format&fit=crop',
    bedrooms: 7,
    bathrooms: 9,
    area: 1500,
    type: PropertyType.MANSION,
    description: 'Obra maestra de la arquitectura con vistas al Arco y al Océano Pacífico. Espacios diseñados para el entretenimiento a gran escala.',
    amenities: ['Piscina Infinita', 'Cine en Casa', 'Spa', 'Cava de Vinos', 'Helipuerto'],
    isPremium: true
  },
  {
    id: '7',
    title: 'Eco-Villa en la Selva',
    subtitle: 'Sustentabilidad y lujo en armonía con la naturaleza',
    location: 'Tulum, México',
    price: 4200000,
    currency: '$',
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b91d?q=80&w=800&auto=format&fit=crop',
    bedrooms: 4,
    bathrooms: 4,
    area: 320,
    type: PropertyType.VILLA,
    description: 'Santuario privado rodeado de naturaleza exuberante. Diseño biomimético y privacidad absoluta.',
    amenities: ['Paneles Solares', 'Cenote Privado', 'Yoga Deck', 'Seguridad 24/7'],
    isPremium: true
  },

  // --- Propiedades Octava Región (Nuevas) ---
  {
    id: 'cl-1',
    title: 'Casa Estilo Georgiano en Lonco Parque',
    subtitle: 'Tradición y elegancia en el sector más exclusivo',
    location: 'Chiguayante, Chile',
    price: 18500,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-2a434f678417?q=80&w=800&auto=format&fit=crop',
    bedrooms: 5,
    bathrooms: 4,
    area: 420,
    type: PropertyType.MANSION,
    description: 'Exclusiva propiedad en el sector más consolidado de Chiguayante con amplios jardines formados, piscina temperada y quincho independiente.',
    amenities: ['Calefacción Central', 'Piscina Temperada', 'Quincho', 'Estacionamiento Techado', 'Jardín Formado'],
    isPremium: false
  },
  {
    id: 'cl-2',
    title: 'Penthouse con Vista al Río Biobío',
    subtitle: 'Vistas panorámicas inigualables sobre el río y el mar',
    location: 'San Pedro de la Paz, Chile',
    price: 12500,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?q=80&w=800&auto=format&fit=crop',
    bedrooms: 3,
    bathrooms: 3,
    area: 210,
    type: PropertyType.PENTHOUSE,
    description: 'Penthouse dúplex en Condominio Andalué. Terrazas amplias, acabados de lujo y acceso controlado.',
    amenities: ['Vista Panorámica', 'Jacuzzi', 'Conserjería 24/7', 'Gimnasio', '2 Estacionamientos'],
    isPremium: false
  },
  {
    id: 'cl-3',
    title: 'Casona Patronal Remodelada',
    subtitle: 'Historia viva con comodidades modernas',
    location: 'Los Ángeles, Chile',
    price: 25000,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?q=80&w=800&auto=format&fit=crop',
    bedrooms: 8,
    bathrooms: 6,
    area: 850,
    type: PropertyType.ESTATE,
    description: 'Finca histórica a minutos del centro, ideal para proyecto hotelero o residencia de lujo. Parque de 5 hectáreas con árboles centenarios.',
    amenities: ['Parque Privado', 'Casa de Huéspedes', 'Caballerizas', 'Pozo Profundo'],
    isPremium: true
  },
  {
    id: 'cl-4',
    title: 'Departamento Moderno Centro',
    subtitle: 'Vida urbana con estilo frente al Parque Ecuador',
    location: 'Concepción, Chile',
    price: 8500,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800&auto=format&fit=crop',
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    type: PropertyType.APARTMENT,
    description: 'Ubicación privilegiada frente al pulmón verde de la ciudad. Cocina integrada equipada y ventanas termopanel.',
    amenities: ['Ubicación Céntrica', 'Termopanel', 'Cocina Equipada', 'Bodega'],
    isPremium: false
  },
  {
    id: 'cl-5',
    title: 'Casa Mediterránea en El Venado',
    subtitle: 'Vanguardia y diseño en el barrio alto',
    location: 'San Pedro de la Paz, Chile',
    price: 22000,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop',
    bedrooms: 6,
    bathrooms: 5,
    area: 380,
    type: PropertyType.VILLA,
    description: 'Arquitectura de vanguardia con espacios de doble altura y luminosidad excepcional. Emplazada en el exclusivo sector de El Venado.',
    amenities: ['Doble Altura', 'Quincho Integrado', 'Piscina', 'Riego Automático', 'Seguridad'],
    isPremium: true
  },
  {
    id: 'cl-6',
    title: 'Parcela de Agrado con Vista al Mar',
    subtitle: 'Refugio natural en la costa',
    location: 'Penco, Chile',
    price: 9500,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=800&auto=format&fit=crop',
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    type: PropertyType.ESTATE,
    description: 'Tranquilidad absoluta en sector Lirquén, rodeado de bosque nativo y con vista despejada a la bahía.',
    amenities: ['Vista al Mar', 'Bosque Nativo', 'Agua de Vertiente', 'Terraza Panorámica'],
    isPremium: false
  },
  {
    id: 'cl-7',
    title: 'Departamento Duplex Puerto',
    subtitle: 'Conexión con el mar y la ciudad',
    location: 'Talcahuano, Chile',
    price: 6800,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1560185008-b033106af5c3?q=80&w=800&auto=format&fit=crop',
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    type: PropertyType.APARTMENT,
    description: 'Vista despejada a la bahía, sector Brisas del Sol, cercano a Casino y servicios.',
    amenities: ['Vista a la Bahía', 'Cercano a Casino', 'Estacionamiento', 'Balcón'],
    isPremium: false
  }
];