import { Property, PropertyType, ListingType } from './types';

export const COMMUNES = [
  'Concepción',
  'San Pedro de la Paz'
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'espectacular-1',
    title: 'Residencia San Pedro del Valle',
    subtitle: 'Arquitectura orgánica y vistas ininterrumpidas al lago',
    location: 'San Pedro de la Paz, Chile',
    price: 32500,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1200&auto=format&fit=crop',
    bedrooms: 5,
    bathrooms: 6,
    area: 580,
    landArea: 1200,
    parking: 4,
    type: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    description: 'Esta impresionante propiedad de diseño contemporáneo destaca por su integración total con el entorno natural. El uso extensivo de maderas nobles en cielos y muros, junto a ventanales de piso a cielo, crean una experiencia de vida única frente al lago. Incluye cocina de alta gama con isla de cuarzo y una terraza panorámica que redefine el concepto de exterior.',
    amenities: ['Muelle Privado', 'Cielos de Madera', 'Cocina de Autor', 'Terraza Panorámica', 'Domótica'],
    isPremium: true,
    categoryImages: [
      { category: 'Exterior', imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=600&auto=format&fit=crop' },
      { category: 'Living', imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=600&auto=format&fit=crop' },
      { category: 'Kitchen', imageUrl: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?q=80&w=600&auto=format&fit=crop' },
      { category: 'Bedrooms', imageUrl: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=600&auto=format&fit=crop' },
      { category: 'Bathrooms', imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=600&auto=format&fit=crop' },
      { category: 'Other', imageUrl: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?q=80&w=600&auto=format&fit=crop' }
    ]
  },
  {
    id: '1',
    title: 'Villa Moderna Lonco',
    subtitle: 'Lujo costero redefinido en el sector más exclusivo',
    location: 'Concepción, Chile',
    price: 45000,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
    bedrooms: 5,
    bathrooms: 6,
    area: 650,
    landArea: 2000,
    parking: 6,
    type: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    description: 'Espectacular villa moderna con vistas panorámicas y terminaciones de lujo.',
    amenities: ['Piscina Privada', 'Vista Panorámica', 'Seguridad 24/7'],
    isPremium: true
  },
  {
    id: 'cl-1',
    title: 'Casa Estilo Georgiano en Idahue',
    subtitle: 'Tradición y elegancia en San Pedro',
    location: 'San Pedro de la Paz, Chile',
    price: 18500,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-2a434f678417?q=80&w=1200&auto=format&fit=crop',
    bedrooms: 5,
    bathrooms: 4,
    area: 420,
    landArea: 800,
    parking: 3,
    type: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    description: 'Exclusiva propiedad en el sector más consolidado de San Pedro de la Paz.',
    amenities: ['Calefacción Central', 'Piscina Temperada'],
    isPremium: false
  },
  {
    id: 'dept-peninsula',
    title: 'Departamento Exclusivo 3D Península',
    subtitle: 'Diseño vanguardista con finas terminaciones frente a la laguna',
    location: 'San Pedro de la Paz, Chile',
    price: 10700,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
    bedrooms: 3,
    bathrooms: 3,
    area: 185,
    parking: 2,
    type: PropertyType.APARTMENT,
    listingType: ListingType.SALE,
    description: 'Departamento de lujo con vistas espectaculares, terraza equipada, cocina italiana con isla y finas maderas.',
    amenities: ['Vista a la Laguna', 'Cocina Italiana', 'Piscina', 'Gimnasio'],
    isPremium: true
  },
  {
    id: 'house-quinta',
    title: 'Residencia de Autor Quinta Junge',
    subtitle: 'Arquitectura contemporánea y máxima privacidad',
    location: 'Concepción, Chile',
    price: 28000,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop',
    bedrooms: 4,
    bathrooms: 5,
    area: 490,
    landArea: 1100,
    parking: 4,
    type: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    description: 'Elegante residencia diseñada para aprovechar la luz natural y las áreas verdes rodeadas de árboles centenarios.',
    amenities: ['Jardín Paisajístico', 'Piscina', 'Cava de Vinos', 'Domótica Completa'],
    isPremium: true
  },
  {
    id: 'dept-duplex',
    title: 'Penthouse Duplex Pedro de Valdivia',
    subtitle: 'Espacios dobles y terraza con quincho privado',
    location: 'Concepción, Chile',
    price: 16900,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
    bedrooms: 4,
    bathrooms: 4,
    area: 280,
    parking: 3,
    type: PropertyType.APARTMENT,
    listingType: ListingType.SALE,
    description: 'Exclusivo penthouse duplex con acabados premium, terraza panorámica de 80m² y seguridad de estándar embajada.',
    amenities: ['Quincho Privado', 'Vista Panorámica', 'Seguridad 24/7', 'Bodega Amplia'],
    isPremium: false
  },
  {
    id: 'rent-1',
    title: 'Penthouse de Lujo en Concepción',
    subtitle: 'Vistas panorámicas y terminaciones de primer nivel',
    location: 'Concepción, Chile',
    price: 120,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
    bedrooms: 3,
    bathrooms: 3,
    area: 210,
    parking: 2,
    type: PropertyType.APARTMENT,
    listingType: ListingType.RENT,
    description: 'Exclusivo penthouse amoblado en el corazón de Concepción. Seguridad 24/7 y acceso directo a servicios.',
    amenities: ['Amoblado', 'Gimnasio', 'Seguridad 24/7'],
    isPremium: true
  },
  {
    id: 'terreno-1',
    title: 'Terreno Industrial San Pedro',
    subtitle: 'Ubicación estratégica con gran potencial',
    location: 'San Pedro de la Paz, Chile',
    price: 15000,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
    bedrooms: 0,
    bathrooms: 0,
    area: 5000,
    landArea: 5000,
    parking: 0,
    type: PropertyType.LAND,
    listingType: ListingType.SALE,
    description: 'Terreno plano con excelente conectividad, ideal para desarrollo industrial o comercial.',
    amenities: ['Factibilidad Eléctrica', 'Agua Potable'],
    isPremium: false
  },
  {
    id: 'parcela-1',
    title: 'Parcela de Agrado Lonco',
    subtitle: 'Naturaleza y tranquilidad a minutos de la ciudad',
    location: 'Concepción, Chile',
    price: 8500,
    currency: 'UF',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
    bedrooms: 0,
    bathrooms: 0,
    area: 0,
    landArea: 5000,
    parking: 0,
    type: PropertyType.PARCEL,
    listingType: ListingType.SALE,
    description: 'Hermosa parcela con bosque nativo y vista al río. El lugar perfecto para construir tu casa soñada.',
    amenities: ['Bosque Nativo', 'Vista al Río'],
    isPremium: false
  }
];
